name: ci
on:
  push:
    branches:
      - master
      - main
      
    workflow_dispatch:
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: [2.7, 3.5, 3.6, 3.7, 3.8]
      - run: pip install mkdocs
      - run: mkdocs gh-deploy
